#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import uuid
import agent
import agent.tasks

data = json.load(sys.stdin)

path = uuid.uuid4().hex
agent.set_env("NODE_EXPORTER_PATH", path)

# Configure Traefik to route "/kickstart" path requests to the kickstart service
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url':  'http://127.0.0.1:9100',
        'http2https': False,
        'lets_encrypt': False,
        'path': f'/{path}',
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

agent.dump_env()
