#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

'''
Expose metrics.
'''

import os
import json

import agent

# expose service provider
ro_redis_client = agent.redis_connect(use_replica=True)
host = ro_redis_client.hget(f'node/{os.environ["NODE_ID"]}/vpn', 'ip_address')

redis_client = agent.redis_connect(privileged=True)
module_id = os.environ["MODULE_ID"]

data = {
    "hosts": [
        host
    ],
    "labels": {
        "__metrics_path__": os.environ["NODE_EXPORTER_PATH"]
    }
}
redis_client.hset(f'module/{module_id}/srv/http/prometheus-metrics', 'config', json.dumps(data))
redis_client.publish(f'module/{module_id}/event/service-prometheus-metrics-updated', '{}')
