#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

'''
Remove exposed metrics.
'''

import os

import agent

# remove configuration
with agent.redis_connect(privileged=True) as redis_client:
    module_id = os.environ["MODULE_ID"]
    redis_client.delete(f'module/{module_id}/srv/http/prometheus-metrics')
    redis_client.publish(f'module/{module_id}/event/service-prometheus-metrics-updated', '{}')
